services:
  sphinx:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile-local
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    container_name: docs-${ENVIRONMENT}
    restart: unless-stopped
    volumes:
      - ./source:/docs/source
    ports:
      - ${LOCAL_PORT}:8000
