FROM python:3.12-alpine3.22

ARG ENVIRONMENT
ENV ENVIRONMENT=${ENVIRONMENT:-production}

# Install UV
RUN pip install uv

# Set working directory
WORKDIR /docs

# Copy project files
COPY pyproject.toml ./
COPY uv.lock ./

# Install dependencies using UV
RUN uv sync --frozen

# Expose port
EXPOSE 8000

CMD ["uv", "run", "sphinx-autobuild", "--host", "0.0.0.0", "--port", "8000", "--builder", "dirhtml", "/docs/source", "/docs/_build"]