#!/usr/bin/env groovy

pipeline {
    agent {
        label "staging"
    }
    environment {
        CIRCLE_CI_TOKEN = credentials('CIRCLE_CI_TOKEN')
        JENKINS_BUILD_USER_ID = ""
        LOCAL_PORT="8080"
        SLACK_CHANNEL = "deploy"
        SLACK_HEADER = "<${RUN_DISPLAY_URL}|${JOB_NAME}>\nResult: "
        SLACK_FOOTER = "Executed on: *${NODE_NAME}*"
    }
    triggers {
        pollSCM('* * * * *') // Polls SCM every minute
    }
    parameters {
        choice(name: "DEPLOY_COMMAND",
                choices: ["deploy", "ci_status"],
                description: "DEPLOY - Start the default deployment\nCI_STATUS - Check the CircleCI build status")
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '15', daysToKeepStr: '14'))
        disableConcurrentBuilds()
        parallelsAlwaysFailFast()
        ansiColor('xterm')
    }
    stages {
        stage('Preparation') {
            steps {
                script {
                    JENKINS_BUILD_CAUSE = "${currentBuild.buildCauses.shortDescription}"
                    wrap([$class: 'BuildUser']) {
                        JENKINS_BUILD_USER_ID = "${BUILD_USER_ID}"
                        currentBuild.displayName = "${JOB_BASE_NAME}-${BUILD_NUMBER}"
                        currentBuild.description = "Build by ${JENKINS_BUILD_USER_ID}"
                    }
                    if (env.BRANCH_NAME == 'master') {
                        env.HOST_ENV = '10.200.1.200'
                        env.JENKINS_CRED_ID = 'ssh-jenkins-to-prod1-wp-nginx'
                        env.ENVIRONMENT="production"
                        env.PRODUCTION_HOST="docs.talkable.com"
                    } else if (env.BRANCH_NAME == 'staging') {
                        env.HOST_ENV = '10.1.2.12'
                        env.JENKINS_CRED_ID = 'ssh-jenkins-to-bastion-wp-nginx'
                        env.ENVIRONMENT="staging"
                        env.STAGING_HOST="docs.bastion.talkable.com"
                    } else {
                        echo "Hello from ${BRANCH_NAME} branch! We only build the following branches of the Talkable repository: master, staging."
                        error("Non-supported branch for build")
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: "${JENKINS_CRED_ID}", keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER')]) {
                        sh "$WORKSPACE/deploy/deploy.sh ${DEPLOY_COMMAND}"
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Build was a success'
            slackSend(channel: "${SLACK_CHANNEL}", color: "#156e2a", message: "${SLACK_HEADER} *${currentBuild.result}!* \n${SLACK_FOOTER}\n${JENKINS_BUILD_CAUSE}")
        }
        failure {
            echo 'Build failed'
            slackSend(channel: "${SLACK_CHANNEL}", color: "#f00101", message: "${SLACK_HEADER} *${currentBuild.result}!* \n${SLACK_FOOTER}\n${JENKINS_BUILD_CAUSE}")
        }
        unstable {
            echo 'Build is unstable'
            slackSend(channel: "${SLACK_CHANNEL}", color: '#f5f63a', message: "${SLACK_HEADER} *${currentBuild.result}!* \n${SLACK_FOOTER}\n${JENKINS_BUILD_CAUSE}")
        }
        aborted {
            echo 'Build was aborted'
            slackSend(channel: "${SLACK_CHANNEL}", color: '#f5f63a', message: "${SLACK_HEADER} *${currentBuild.result}!* \n${SLACK_FOOTER}\n${JENKINS_BUILD_CAUSE}")
        }
        cleanup {
            echo 'Performing cleanup'
            cleanWs cleanWhenFailure: false,
                    cleanWhenUnstable: true,
                    cleanWhenAborted: true,
                    cleanWhenNotBuilt: true,
                    cleanWhenSuccess: true,
                    deleteDirs: true,
                    notFailBuild: true
        }
    }
}
