#!/usr/bin/env groovy

// Upgrades or installs nginx containers for WordPress.
def dockerContainerUpdate(String hostEnv) {
    sh """ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SSH_USER@${hostEnv} 'cd talkable-docs/ && \
        git checkout ${BRANCH_NAME} && git branch -a && git pull origin && \
        docker-compose ls && docker ps && \
        docker-compose down && docker-compose up -d --remove-orphans && \
        docker-compose ls && docker ps' """
}

pipeline {
    agent {
        label "staging"
    }
    environment {
        GITHUB_ACC = credentials('talkable-bot-deploy-token')
        JENKINS_BUILD_USER_ID = ""
//        CHANGESET_REGEXP = "^nginx/.*"
    }
    triggers {
        pollSCM('* * * * *') // Polls SCM every minute
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '15', daysToKeepStr: '14'))
        disableConcurrentBuilds()
        parallelsAlwaysFailFast()
        ansiColor('xterm')
    }
    stages {
        stage('Preparation') {
            steps {
                script {
                    wrap([$class: 'BuildUser']) {
                        JENKINS_BUILD_USER_ID = "${BUILD_USER_ID}"
                        currentBuild.displayName = "${JOB_BASE_NAME}-${BUILD_NUMBER}"
                        currentBuild.description = "Build by ${JENKINS_BUILD_USER_ID}"
                    }
                    if (env.BRANCH_NAME == 'master') {
                        env.HOST_ENV = '10.200.1.200'
                        env.JENKINS_CRED_ID = 'ssh-jenkins-to-prod1-wp-nginx'
                    } else if (env.BRANCH_NAME == 'staging') {
                        env.HOST_ENV = '10.1.2.12'
                        env.JENKINS_CRED_ID = 'ssh-jenkins-to-bastion-wp-nginx'
                    } else {
                        echo "Hello from ${BRANCH_NAME} branch! We only build the following branches of the Talkable repository: master, staging."
                        error("Non-supported branch for build")
                    }
                }
            }
        }
        stage('Build') {
//            when {
//                beforeAgent true
//                changeset pattern: "${CHANGESET_REGEXP}", comparator: "REGEXP"
//            }
            steps {
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: "${JENKINS_CRED_ID}", keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER')]) {
                        dockerContainerUpdate('$HOST_ENV')
                    }
                }
            }
        }
        stage('Manual-build') {
            when {
                not
                        {
                            triggeredBy 'SCMTrigger'
                        }
            }
            steps {
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: "${JENKINS_CRED_ID}", keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER')]) {
                        dockerContainerUpdate('$HOST_ENV')
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Build was a success'
        }
        failure {
            echo 'Build failed'
        }
        unstable {
            echo 'Build is unstable'
        }
        aborted {
            echo 'Build was aborted'
        }
        cleanup {
            echo 'Performing cleanup'
            cleanWs cleanWhenFailure: false,
                    cleanWhenUnstable: true,
                    cleanWhenAborted: true,
                    cleanWhenNotBuilt: true,
                    cleanWhenSuccess: true,
                    deleteDirs: true,
                    notFailBuild: true
        }
    }
}
